### ISSUE TITLE
environment.yml does not work with Conda

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#19]
**Describe the bug**
environment.yml is not functional as of right now on SSH

**To Reproduce**
1. Log into SSH
2. cd into brain-segm
3. Create a new Conda environment based on environment.yml

**Expected behavior**
The right packages are downloaded and the new Conda environment is created.

**Actual behavior**
Either it will report the following packages as not found:
```
ResolvePackageNotFound: 
  - torchaudio
  - ignite
```
Or, if we exclude the invalid packages, it will remain on
```
Solving environment: |
```
Until terminated.

**Comment by gromdimon** [comment]
Another conda env file was added in a73654a4c304274c8786f957356847e2b08ab9f1
