### ISSUE TITLE
Explore data augmentation

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#21]
Check docs/optimizations.md

**Comment by gromdimon** [comment]
## Some useful links
Our Docs: https://github.com/gromdimon/brain-segment/blob/main/docs/optimizations.md#augment-our-training-set
Monai transforms: https://docs.monai.io/en/stable/transforms.html
Torchvision: https://pytorch.org/vision/stable/transforms.html
volumentations: https://github.com/ZFTurbo/volumentations

The step of data augmentation is probably the one, which we need at the end of our experimentation/investigation: the larger ammount of data is almost every time good (except of overtraining). So, we should:
Find a way to augment the data 
Write the augmentation function/class in `utility.py`
Write example notebook, how to use this utility function.
At the end - train the model on the whole dataset.

**Comment by mathiashusted** [comment]
Probably won't have time for this
