### ISSUE TITLE
Explore the optimal number of epochs

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#22]
Check docs/optimizations.md

**Comment by gromdimon** [comment]
Our docs: https://github.com/gromdimon/brain-segment/blob/main/docs/optimizations.md#epochs

General comment:
Probably we'll just need to run the whole training one time and see the logs and statistics from it. We also have the example plots in the jupyter notebook (about training the UNet). So we just need to make **a big run**.

**Comment by gromdimon** [comment]
From here: gromdimon/brain-segmentation/csl45bdi it looks like the 30 epochs is just enough

**Comment by mathiashusted** [comment]
We'll test this anyways (low hanging fruit, it will run overnight)

**Comment by mathiashusted** [comment]
Ok, it seems that 30 is indeed optimal.
