### ISSUE TITLE
Explore activation functions

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#23]
Check docs/optimizations.md

**Comment by gromdimon** [comment]
Our docs: https://github.com/gromdimon/brain-segment/blob/main/docs/optimizations.md#activation-function
MONAI UNet: https://docs.monai.io/en/stable/networks.html#unet

All possibles Activating functions in MONAI ([source](https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/layers/factories.py#L287)):
```
Act.add_factory_class("elu", nn.modules.ELU)
Act.add_factory_class("relu", nn.modules.ReLU)
Act.add_factory_class("leakyrelu", nn.modules.LeakyReLU)
Act.add_factory_class("prelu", nn.modules.PReLU)
Act.add_factory_class("relu6", nn.modules.ReLU6)
Act.add_factory_class("selu", nn.modules.SELU)
Act.add_factory_class("celu", nn.modules.CELU)
Act.add_factory_class("gelu", nn.modules.GELU)
Act.add_factory_class("sigmoid", nn.modules.Sigmoid)
Act.add_factory_class("tanh", nn.modules.Tanh)
Act.add_factory_class("softmax", nn.modules.Softmax)
Act.add_factory_class("logsoftmax", nn.modules.LogSoftmax)
```

We need to:
Create small subset (and small number of epochs)
Run this experiment with different activation functions
Compare results on W&B
