### ISSUE TITLE
Explore optimizers and learning rate schedulers

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#25]
Check docs/optimizations.md

**Comment by gromdimon** [comment]
Our docs: https://github.com/gromdimon/brain-segment/blob/main/docs/optimizations.md#optimizer

TODO:
1) Run all possible optimization on optimizers
2) Compare results on W&B

**Comment by mathiashusted** [comment]
Thanks @evin222 . Adam is optimal
