### ISSUE TITLE
Adjust the model architecture

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#27]
Check docs/optimizations.md

**Comment by gromdimon** [comment]
This is the most powerful and important adjustment. 
We should first finish #22 #23 #24 #25 #26. 
Secondly, we need to make the model as small as possible!

Also this seems to be one of the final steps at this project (so let's pay more attention to it)

**Comment by mathiashusted** [comment]
Managed to get the channel numbers from (16, 32, 64) to (8, 16, 64) with a minimal dice val loss, but in turn a performance boost.
